# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build 32-bit
        run: go build -v -o build32/donation-vts.exe .
        env:
          GOOS: windows
          GOARCH: 386
        
      - name: Build 64-bit
        run: go build -v -o build64/donation-vts.exe .
        env:
          GOOS: windows
          GOARCH: amd64
        
      - name: Compress 32-bit
        run: zip -j "donation-vts(32-bit).zip" build32/donation-vts.exe config.json README.md README-RU.md LICENSE "Authorize Donationalerts.url"

      - name: Compress 64-bit
        run: zip -j "donation-vts(64-bit).zip" build64/donation-vts.exe config.json README.md README-RU.md LICENSE "Authorize Donationalerts.url"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
      
      - name: Upload 32-bit Build
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./donation-vts(32-bit).zip
          asset_name: donation-vts(32-bit).zip
          asset_content_type: application/zip

      - name: Upload 64-bit Build
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./donation-vts(64-bit).zip
          asset_name: donation-vts(64-bit).zip
          asset_content_type: application/zip

